dist: xenial
language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"

sudo: false

addons:
    postgresql: "10"
    apt:
      packages:
        - postgresql-10-postgis-2.4

services:
    - postgresql
    - elasticsearch

install:
    - pip install -r requirements.txt

env:
    - GOOGLE_API_KEY=NOT_A_VALID_KEY

before_script:
    - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.6/elasticsearch-2.4.6.deb && sudo dpkg -i --force-confnew elasticsearch-2.4.6.deb && sudo service elasticsearch restart
    - sleep 10
    - psql -U postgres -c 'create user invasives;'
    - psql -U postgres -c 'create database invasives owner invasives;'
    - psql -U postgres -d invasives -c 'create extension postgis;'
    - psql -U postgres -c 'create database test_invasives owner invasives;'
    - psql -U postgres -d test_invasives -c 'create extension postgis;'
    - curl -XPUT 'http://localhost:9200/oregoninvasiveshotline-test/'

script:
    - LOCAL_SETTINGS_FILE="local.base.cfg#travis" python manage.py test --keepdb
