language: python
python:
  - "3.3"
sudo: false
# command to install dependencies
install:
  - make init
# command to run tests
script: make test
services:
  - elasticsearch
before_script:
  - sleep 10
