version: '3.7'
networks:
  overlay:
    driver: overlay
    attachable: true
services:
  postgresql:
    image: postgis/postgis:11-2.5
    networks:
    - overlay
    volumes:
    - type: tmpfs
      target: /dev/shm
      tmpfs:
        size: 1073741824
    - /etc/localtime:/etc/localtime:ro
    - /etc/passwd:/etc/passwd:ro
    - /vol/store/services/postgresql/data:/var/lib/postgresql/data
    - /vol/store/services/postgresql/archive:/opt/archive
    logging:
      driver: json-file
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
    user: 1100:1100
  rabbitmq:
    image: rabbitmq:3-alpine
    networks:
    - overlay
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/passwd:/etc/passwd:ro
    - /vol/store/services/rabbitmq:/var/lib/rabbitmq
    logging:
      driver: json-file
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
    hostname: rabbitmq-prod
    user: 1100:1100
  app:
    image: ghcr.io/psu-oit-arc/oregoninvasiveshotline/app-cloud:1.16.2
    networks:
    - overlay
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/passwd:/etc/passwd:ro
    - /vol/store/media:/vol/store/media
    - /vol/www/oregoninvasiveshotline:/vol/www/oregoninvasiveshotline
    - ./uwsgi:/uwsgi
    - ./:/app
    environment:
    - EMCEE_CMD_ENV=cloud
    - APP_SERVICE=wsgi
    logging:
      driver: json-file
    deploy:
      replicas: 1
    user: invasives:invasives
  celery:
    image: ghcr.io/psu-oit-arc/oregoninvasiveshotline/app-cloud:1.16.2
    networks:
    - overlay
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/passwd:/etc/passwd:ro
    - /vol/store/media:/vol/store/media
    - /vol/www/oregoninvasiveshotline:/vol/www/oregoninvasiveshotline
    - ./:/app
    environment:
    - EMCEE_CMD_ENV=cloud
    - APP_SERVICE=celery
    logging:
      driver: json-file
    deploy:
      replicas: 1
    depends_on:
    - rabbitmq
    user: invasives:invasives
  scheduler:
    image: ghcr.io/psu-oit-arc/oregoninvasiveshotline/app-cloud:1.16.2
    networks:
    - overlay
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/passwd:/etc/passwd:ro
    - /vol/store/media:/vol/store/media
    - /vol/www/oregoninvasiveshotline:/vol/www/oregoninvasiveshotline
    - ./:/app
    environment:
    - EMCEE_CMD_ENV=cloud
    - APP_SERVICE=scheduler
    logging:
      driver: json-file
    deploy:
      replicas: 1
    depends_on:
    - rabbitmq
    user: invasives:invasives
  proxy:
    image: nginx:stable
    networks:
    - overlay
    ports:
    - target: 80
      published: 80
      protocol: tcp
      mode: host
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /vol/store/media:/media
    - /vol/www/oregoninvasiveshotline/static:/static
    - ./nginx/invasives.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/host_defaults.conf:/etc/nginx/host_defaults.conf
    - ./nginx/server_defaults.conf:/etc/nginx/server_defaults.conf
    - ./nginx-custom/maintenance.conf:/etc/nginx/conf.d/maintenance.conf
    logging:
      driver: json-file
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
    depends_on:
    - app
