version: '3'
services:
  app:
    image: ghcr.io/psu-oit-arc/oregoninvasiveshotline/app-cloud:1.16.2
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
      - APP_USER_ID=1100
      - APP_GROUP_ID=1100
