version: '2.4'


networks:
  services:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: oregoninvasiveshotline_rabbitmq_1
    networks:
      - services
    ports:
      - 127.0.0.1:5672:5672
    volumes:
      - /vol/www/oregoninvasiveshotline/services/rabbitmq:/var/lib/rabbitmq
    # override hostname to prevent reinitialization of data
    # on container delete/init cycle.
    #   Refs: https://github.com/docker-library/rabbitmq/issues/106#issuecomment-241882358
    hostname: 'rabbitmq'
    user: "1101"
    mem_limit: 256M
    mem_swappiness: 1
    restart: always
