version: '2.4'


networks:
  services:
    driver: bridge

services:
  elasticsearch:
    image: elasticsearch:2
    command: elasticsearch --network.host=_eth0_ --discovery.zen.ping.multicast.enabled=false --discovery.zen.ping.unicast.hosts=elasticsearch-node-1,elasticsearch-node-2 --node.master=true --node.data=false
    environment:
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    networks:
      - services
    ports:
      - 127.0.0.1:9200:9200
    volumes:
      - /vol/www/oregoninvasiveshotline/services/elasticsearch/master:/usr/share/elasticsearch/data
    hostname: 'elasticsearch'
    user: "1008"
    mem_limit: 256M
    mem_swappiness: 1
    restart: always

  elasticsearch-node-1:
    image: elasticsearch:2
    command: elasticsearch --network.host=_eth0_ --discovery.zen.ping.multicast.enabled=false --discovery.zen.ping.unicast.hosts=elasticsearch --node.master=false --node.data=true
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    networks:
      - services
    volumes:
      - /vol/www/oregoninvasiveshotline/services/elasticsearch/node-1:/usr/share/elasticsearch/data
    hostname: 'elasticsearch-node-1'
    user: "1008"
    restart: always
    cpus: 1
    mem_limit: 512M
    mem_swappiness: 1
    ulimits:
      memlock:
        soft: -1
        hard: -1

  elasticsearch-node-2:
    image: elasticsearch:2
    command: elasticsearch --network.host=_eth0_ --discovery.zen.ping.multicast.enabled=false --discovery.zen.ping.unicast.hosts=elasticsearch --node.master=false --node.data=true
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    networks:
      - services
    volumes:
      - /vol/www/oregoninvasiveshotline/services/elasticsearch/node-2:/usr/share/elasticsearch/data
    hostname: 'elasticsearch-node-2'
    user: "1008"
    restart: always
    cpus: 1
    mem_limit: 512M
    mem_swappiness: 1
    ulimits:
      memlock:
        soft: -1
        hard: -1

  rabbitmq:
    image: rabbitmq:3-alpine
    networks:
      - services
    ports:
      - 127.0.0.1:5672:5672
    volumes:
      - /vol/www/oregoninvasiveshotline/services/rabbitmq:/var/lib/rabbitmq
    # override hostname to prevent reinitialization of data
    # on container delete/init cycle.
    #   Refs: https://github.com/docker-library/rabbitmq/issues/106#issuecomment-241882358
    hostname: 'rabbitmq'
    user: "1008"
    mem_limit: 256M
    mem_swappiness: 1
    restart: always
