version: "2.4"


networks:
  default:
    driver: bridge
    ipam:
      config:
        # this value is a soft-reservation of the subnet in
        # order to reduce friction w.r.t. a given local docker
        # environment and project configuration.
        #
        # if you encounter network definition conflicts, change
        # the value below and revise its use in 'local.*.cfg'.
        - subnet: 172.23.0.0/16

services:
  postgres:
    image: kartoza/postgis:10.0-2.4
    networks:
      - default
    environment:
      # In some cases, the logic present in the kartoza/postgis
      # entrypoint may fail to recognize that this database already
      # exists when the container volume has already such a database
      # present; in this case, comment the 'POSTGRES_DBNAME' entry
      # in order to succesfully boot the container.
      - POSTGRES_USER=invasives
      - POSTGRES_PASS=invasives
      - POSTGRES_DBNAME=invasives
      - ALLOW_IP_RANGE=172.23.0.0/16
    volumes:
      - ./volumes/postgres:/var/lib/postgresql

  elasticsearch:
    image: elasticsearch:2
    networks:
      - default
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data

  rabbitmq:
    image: rabbitmq:3-alpine
    networks:
      - default
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    # override hostname to prevent reinitialization of data
    # on container delete/init cycle.
    #   Refs: https://github.com/docker-library/rabbitmq/issues/106#issuecomment-241882358
    hostname: 'rabbitmq-dev'

  app:
    build: docker
    environment:
      - LOCAL_SETTINGS_FILE=local.docker.cfg
      - APP_SERVICE=wsgi
      - GOOGLE_API_KEY=
    networks:
      - default
    ports:
      - 8000:8000
    volumes:
      - ./:/webapps/oregoninvasiveshotline
      - ./volumes/media:/webapps/oregoninvasiveshotline/media
    depends_on:
      - postgres
      - elasticsearch
      - rabbitmq

  celery:
    build: docker
    environment:
      - LOCAL_SETTINGS_FILE=local.docker.cfg
      - APP_SERVICE=celery
      - GOOGLE_API_KEY=
    networks:
      - default
    volumes:
      - ./:/webapps/oregoninvasiveshotline
      - ./volumes/media:/webapps/oregoninvasiveshotline/media
    depends_on:
      - app

  test:
    build: docker
    environment:
      - LOCAL_SETTINGS_FILE=local.test.cfg
      - APP_SERVICE=test
      - GOOGLE_API_KEY=
    networks:
      - default
    volumes:
      - ./:/webapps/oregoninvasiveshotline
    depends_on:
      - postgres
      - elasticsearch
      - rabbitmq
