version: '3'
services:
  app:
    image: ghcr.io/psu-oit-arc/oregoninvasiveshotline/app-stage:1.15.12
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
      - APP_USER_ID=1101
      - APP_GROUP_ID=1101
