# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usernotificationquery',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
