AWSTemplateFormatVersion: '2010-09-09'
Description: Resource stack for Oregon Invasives Hotline
Resources:
  AppRole:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20221006/iam/application_role.template.yml
      Parameters:
        Name: invasives
        VpcStackName: vpc-cloud
  Host:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20221006/ec2/private_host/private_host.template.yml
      Parameters:
        ImageId: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
        ImageDistribution: amazon
        ImageDistributionVersion: 2023
        InstanceType: t3.small
        HostName: !GetAtt 'AppRole.Outputs.Name'
        VpcStackName: !GetAtt 'AppRole.Outputs.VpcStackName'
        IAMAppRoleName: !GetAtt 'AppRole.Outputs.RoleName'
        ExternalZoneName: cloud.wdt.pdx.edu
        InternalZoneName: cloud-internal
        UseEFSFilesystem: true
        EbsDeleteOnTermination: false
        EnableEbsEncryption: true
        EbsKmsKey: !GetAtt 'AppRole.Outputs.KmsKeyArn'
        EbsVolumeId: !GetAtt 'Volume.Outputs.EbsVolume'
  Networking:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20221006/ec2/private_host/networking.template.yml
      Parameters:
        EC2Instance: !GetAtt 'Host.Outputs.InstanceId'
        DnsHostName: !GetAtt 'AppRole.Outputs.Name'
        VpcStackName: !GetAtt 'AppRole.Outputs.VpcStackName'
        ExternalZoneName: !GetAtt 'Host.Outputs.ExternalZoneName'
        ELBListenerPriority: !Ref 'ELBListenerPriority'
        ListenOn80: true
  Volume:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20221006/ec2/ebs/volume.template.yml
      Parameters:
        Name: invasives-cloud
        VolumeSize: 25
        AvailabilityZone: us-west-2a
        EnableEncryption: true
        KmsKey: !GetAtt 'AppRole.Outputs.KmsKeyArn'
        DeletionPolicy: Snapshot
  Domain:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20221006/ec2/private_host/domain.template.yml
      Parameters:
        ZoneExists: true
        HostedZoneName: oregoninvasiveshotline.org
        DnsHostName: oregoninvasiveshotline.org
        ELBCertificate: arn:aws:acm:us-west-2:921749119607:certificate/5c148b9a-bbdc-4739-9cd2-174be1545c9a
        ELBTargetGroup: !GetAtt 'Networking.Outputs.ELBTargetGroup'
        ELBListenerPriority: !Ref 'CustomELBListenerPriority'
        VpcStackName: !GetAtt 'AppRole.Outputs.VpcStackName'
        ListenOn80: true
Parameters:
  ELBListenerPriority:
    Type: String
    Description: Mechanism for declaring ELBListenerPriority
  CustomELBListenerPriority:
    Type: String
    Description: Mechanism for declaring CustomELBListenerPriority
