AWSTemplateFormatVersion: '2010-09-09'
Description: "Resource stack for Oregon Invasives Hotline"
Resources:
  AppRole:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/1/iam/application_role.template.yml
      Parameters:
        Name: invasives
        VpcStackName: vpc-stage
  Host:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/1/ec2/private_host/private_host.template.yml
      Parameters:
        ImageId: ami-d2f06baa
        ImageDistribution: amazon2
        HostName: !GetAtt AppRole.Outputs.Name
        VpcStackName: !GetAtt AppRole.Outputs.VpcStackName
        IAMAppRoleName: !GetAtt AppRole.Outputs.RoleName
        ExternalZoneName: stage.wdt.pdx.edu
        InternalZoneName: stage-internal
        UseEFSFilesystem: true
        EbsVolumeId: !GetAtt Volume.Outputs.EbsVolume
  Networking:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/1/ec2/private_host/networking.template.yml
      Parameters:
        EC2Instance: !GetAtt Host.Outputs.InstanceId
        PrivateIp: !GetAtt Host.Outputs.PrivateIP
        DnsHostName: !GetAtt AppRole.Outputs.Name
        VpcStackName: !GetAtt AppRole.Outputs.VpcStackName
        ExternalZoneName: !GetAtt Host.Outputs.ExternalZoneName
        InternalZoneName: !GetAtt Host.Outputs.InternalZoneName
        ELBListenerPriority: 5
        ListenOn80: true
  PostgreSQL:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/1/rds/postgres.template.yml
      Parameters:
        VpcStackName: !GetAtt AppRole.Outputs.VpcStackName
        AvailabilityZone: us-west-2a
        DBEngineVersion: 9.6
        DBInstanceName: oregoninvasiveshotline
        DBUsername: oregoninvasiveshotline_l
        DBPassword: __GENERATED__
        EC2SecurityGroupId: !GetAtt Host.Outputs.EC2SecurityGroup
  SearchIndex:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/1/es/domain.template.yml
      Parameters:
        VpcStackName: !GetAtt AppRole.Outputs.VpcStackName
        Name: oregoninvasiveshotline-stage
        IamResourceARN: !GetAtt AppRole.Outputs.RoleArn
        EC2SecurityGroupId: !GetAtt Host.Outputs.EC2SecurityGroup
  Volume:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/1/ec2/ebs/volume.template.yml
      Parameters:
        Name: oregoninvasiveshotline-stage
        AvailabilityZone: us-west-2a
        DeletionPolicy: Delete
