AWSTemplateFormatVersion: '2010-09-09'
Description: Resource stack for Oregon Invasives Hotline
Resources:
  AppRole:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20200206/iam/application_role.template.yml
      Parameters:
        Name: invasives
        VpcStackName: vpc-stage
  Host:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20200206/ec2/private_host/private_host.template.yml
      Parameters:
        EbsVolumeId: !GetAtt 'Volume.Outputs.EbsVolume'
        ExternalZoneName: stage.wdt.pdx.edu
        HostName: !GetAtt 'AppRole.Outputs.Name'
        IAMAppRoleName: !GetAtt 'AppRole.Outputs.RoleName'
        InstanceType: t3.small
        ImageDistribution: amazon2
        ImageId: ami-082b5a644766e0e6f
        InternalZoneName: stage-internal
        UseEFSFilesystem: true
        VpcStackName: !GetAtt 'AppRole.Outputs.VpcStackName'

  Networking:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20200206/ec2/private_host/networking.template.yml
      Parameters:
        DnsHostName: !GetAtt 'AppRole.Outputs.Name'
        EC2Instance: !GetAtt 'Host.Outputs.InstanceId'
        ELBListenerPriority: !Ref 'ELBListenerPriority'
        ExternalZoneName: !GetAtt 'Host.Outputs.ExternalZoneName'
        InternalZoneName: !GetAtt 'Host.Outputs.InternalZoneName'
        ListenOn80: true
        PrivateIp: !GetAtt 'Host.Outputs.PrivateIP'
        VpcStackName: !GetAtt 'AppRole.Outputs.VpcStackName'

  PostgreSQL:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20200206/rds/postgres.template.yml
      Parameters:
        AvailabilityZone: us-west-2a
        DBInstanceName: oregoninvasiveshotline-stage
        DBPassword: !Ref 'DBPassword'
        DBUsername: oregoninvasiveshotline_l
        EC2SecurityGroupId: !GetAtt 'Host.Outputs.EC2SecurityGroup'
        VpcStackName: !GetAtt 'AppRole.Outputs.VpcStackName'

  Volume:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20200206/ec2/ebs/volume.template.yml
      Parameters:
        AvailabilityZone: us-west-2a
        Name: oregoninvasiveshotline-stage

Parameters:
  ELBListenerPriority:
    Type: String
    Description: Mechanism for declaring ELBListenerPriority
  DBPassword:
    Type: String
    Description: Mechanism for declaring DBPassword
