# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 21:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_change_default_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='edited_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
